PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE T2 (Id NUMBER PRIMARY KEY);
CREATE TABLE T1 (Id NUMBER PRIMARY KEY, Id2 NUMBER REFERENCES T2(Id));
INSERT INTO T2 VALUES(111);
INSERT INTO T2 VALUES(222);
INSERT INTO T1 VALUES(1,111);
INSERT INTO T1 VALUES(2,333);
COMMIT;

